version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    groups:
      production-dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'
